name: pemobile2_d4rpl3b_praktikum4
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Library untuk tampilan onboarding
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Daftar aset gambar yang digunakan di onboarding screen

  # (Jika ada font custom, bisa tambahkan di sini)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
